Repository Skhuthon/Skhuthon_0th_TEAM02_BE, pull requests merged in 2024-06, with the labels that each got.

#2 [Setting] #1 데이터베이스 설계
  .idea/.gitignore
  .idea/Skhuthon.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/diary/Diary.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/diary/Visibility.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/friend/Friend.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/region/Region.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/region/RegionCategory.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/user/User.java
Labels: Setting, 두오

#4 [Setting] #3 프로젝트 초기 설정
  sweet_little_kitty/build.gradle
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SwaggerConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/exception/ControllerExceptionAdvice.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/exception/CustomException.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/exception/code/ErrorCode.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/exception/code/SuccessCode.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/template/ApiResponseTemplate.java
Labels: Setting, 두오

#10 [Fix] #3 스웨거 설정 수정
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SwaggerConfig.java
Labels: Setting, Fix, 두오

#11 [Fix] #3 테스트를 위한 시큐리티 주석 처리
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
Labels: Setting, Fix, 두오

#13 [Fix] #3 스웨거 수정
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SwaggerConfig.java
Labels: Setting, Fix, 두오

#14 [Fix] #3 스프링 시큐리티 주석 처리
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
Labels: Setting, Fix, 두오

#15 [Fix] #3 스웨거 설정 수정
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SwaggerConfig.java
Labels: Setting, Fix, 두오

#16 [Feature] #5 diary 이미지 관리, diary CRUD
  sweet_little_kitty/build.gradle
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/DiaryController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/DiaryDisplayController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/diary/DiaryDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/diary/request/DiaryRegisterReqDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/diary/response/DiaryRegisterResDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/diary/Diary.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/diary/DiaryRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/region/RegionRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/user/UserRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/auth/KakaoAuthService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryDisplayService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryDisplayServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/S3ImageFileService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/S3ImageFileServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/S3Config.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/security/CustomUserDetailsService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/util/GetS3Resource.java
Labels: Feature, 두오

#19 [Feature] #17 마이페이지 조회
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/user/UserInfoController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/user/response/UserInfoResDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/user/UserInfoService.java
Labels: Feature, 두오

#21 [Feature]: #18 친구 관리 기능 구현
  .idea/sonarlint/issuestore/1/7/17b7cf4851fd573b40d1836464b40c07e1587be5
  .idea/sonarlint/issuestore/2/e/2e8551a4ea6c350f4129f0fcccdfb22fa08ea51f
  .idea/sonarlint/issuestore/3/1/31b5d6033807a2807a7b50c34ad97839a24842d2
  .idea/sonarlint/issuestore/3/2/3247ddf1d65ef7a862449e755d5b16f31541edc9
  .idea/sonarlint/issuestore/3/f/3f7b740d4705dea864da4f13913dc24240be48fd
  .idea/sonarlint/issuestore/5/b/5b4a26264f15e4531ed8d408c4334db3fd849827
  .idea/sonarlint/issuestore/6/1/6101cf09244e71b343ca09850ba09efeb33b6aa0
  .idea/sonarlint/issuestore/6/5/65c0bd5ceda4493668cbf35caf4476e18840caa5
  .idea/sonarlint/issuestore/7/3/7335dbffb77e5b599736d75c82f6c157a0d62d42
  .idea/sonarlint/issuestore/8/9/89341e99777b1e87f3ab93ea41255273e8bf4776
  .idea/sonarlint/issuestore/8/a/8a17a5c8a509458f912809d5833fffebfcd18ee2
  .idea/sonarlint/issuestore/9/e/9e99f9d4f7b4037cd399d4b8bdcfe508b8f6fb4c
  .idea/sonarlint/issuestore/a/0/a077767bf9561c45b3441e05a7c03dc90dd4d52a
  .idea/sonarlint/issuestore/a/3/a3662284562d4c11d4eb3afded86d3b733f8ea26
  .idea/sonarlint/issuestore/a/8/a87e83b3d4e417e884583007c05d59cc22f3093f
  .idea/sonarlint/issuestore/c/5/c522f6b22af2381e85e9e2e0001c062a8a91b077
  .idea/sonarlint/issuestore/f/1/f1130412feb3c39c98df4e5299fff3ce8b144047
  .idea/sonarlint/issuestore/f/9/f99a80e64a4ba37b9966e8bf3d01a28f83e5dee2
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/1/7/17b7cf4851fd573b40d1836464b40c07e1587be5
  .idea/sonarlint/securityhotspotstore/3/1/31b5d6033807a2807a7b50c34ad97839a24842d2
  .idea/sonarlint/securityhotspotstore/3/2/3247ddf1d65ef7a862449e755d5b16f31541edc9
  .idea/sonarlint/securityhotspotstore/5/b/5b4a26264f15e4531ed8d408c4334db3fd849827
  .idea/sonarlint/securityhotspotstore/6/1/6101cf09244e71b343ca09850ba09efeb33b6aa0
  .idea/sonarlint/securityhotspotstore/6/5/65c0bd5ceda4493668cbf35caf4476e18840caa5
  .idea/sonarlint/securityhotspotstore/8/9/89341e99777b1e87f3ab93ea41255273e8bf4776
  .idea/sonarlint/securityhotspotstore/8/a/8a17a5c8a509458f912809d5833fffebfcd18ee2
  .idea/sonarlint/securityhotspotstore/9/e/9e99f9d4f7b4037cd399d4b8bdcfe508b8f6fb4c
  .idea/sonarlint/securityhotspotstore/a/0/a077767bf9561c45b3441e05a7c03dc90dd4d52a
  .idea/sonarlint/securityhotspotstore/a/3/a3662284562d4c11d4eb3afded86d3b733f8ea26
  .idea/sonarlint/securityhotspotstore/a/8/a87e83b3d4e417e884583007c05d59cc22f3093f
  .idea/sonarlint/securityhotspotstore/index.pb
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/auth/AuthController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/friend/FriendController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/friend/request/FriendRequestDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/friend/response/FriendResponseDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/entity/user/User.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/friend/FriendRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/friend/FriendService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/friend/FriendServiceImplementation.java
Labels: Feature, 나윤

#23 [Fix] #22 카카오 로그인 해결
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/user/UserInfoController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/auth/KakaoAuthService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/user/UserInfoService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SecurityConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/security/JwtAuthenticationFilter.java
Labels: Fix, Refactor, 두오

#27 [Refactor] #24 diary CRUD 로직 리팩토링
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/DiaryController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/DiaryDisplayController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/diary/request/DiaryRegisterReqDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryDisplayService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryDisplayServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/DiaryServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/DataInit.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/config/SwaggerConfig.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/security/JwtAuthenticationFilter.java
Labels: Fix, Refactor, 두오

#30 [Refactor]: #29 친구 관리 로직
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/sweet_little_kitty.main.iml
  .idea/sonarlint/issuestore/1/4/14f276da34ca1de990c853394939adf52f49d47a
  .idea/sonarlint/issuestore/5/c/5cdc57326db97a18efac3737d81d1dd58b2563ba
  .idea/sonarlint/issuestore/8/f/8f54becbb719ad12746c9b08b7a6346b4bae76b1
  .idea/sonarlint/issuestore/9/0/90ff5a6790d40e37aae3e1a12d947eb1f69567a0
  .idea/sonarlint/issuestore/9/8/982d545beb8e5b3021fec62d608c4cadcb43ef84
  .idea/sonarlint/issuestore/a/0/a077767bf9561c45b3441e05a7c03dc90dd4d52a
  .idea/sonarlint/issuestore/f/d/fddcf8d9f9e05ad67fbc9e8016528f8555f43f22
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/1/4/14f276da34ca1de990c853394939adf52f49d47a
  .idea/sonarlint/securityhotspotstore/8/f/8f54becbb719ad12746c9b08b7a6346b4bae76b1
  .idea/sonarlint/securityhotspotstore/f/d/fddcf8d9f9e05ad67fbc9e8016528f8555f43f22
  .idea/sonarlint/securityhotspotstore/index.pb
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/friends/FriendsDiaryController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/diary/DiaryRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/friends/FriendsDiaryService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/friends/FriendsDiaryServiceImpl.java
Labels: Refactor, 나윤

#33 [Fix] #32 친구 관리, 조회 로직 수정
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/diary/friends/FriendsDiaryController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/controller/friend/FriendController.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/dto/friend/request/FriendRequestDto.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/repository/friend/FriendRepository.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/diary/friends/FriendsDiaryServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/friend/FriendService.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/app/service/friend/FriendServiceImpl.java
  sweet_little_kitty/src/main/java/com/skhuthon/sweet_little_kitty/global/exception/code/SuccessCode.java
Labels: Fix, Refactor, 두오
